name: Deploy Calcom Stack To Dev
on:
  workflow_run:
    workflows: ["Build and push image to DockerHub"]
    branches: [main]
    types:
      - completed
jobs:
  Deploy-Calcom-Stack:
  
    runs-on: ubuntu-latest
    environment: Dev
    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: Rsync Deployments
      uses: burnett01/rsync-deployments@7.0.1
      with:
        switches: -avzr --delete
        remote_path: /home/ubuntu/calcom
        remote_host: ${{ secrets.REMOTE_HOST }}
        remote_user: ${{ secrets.REMOTE_USER }}
        remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
    
    - name: Install Docker
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |          
          if ! command -v docker &> /dev/null; then
            echo "Docker is not installed. Installing Docker..."
            curl -fsSL https://get.docker.com | bash -
          else
            echo "Docker is already installed."
          fi
          # Check Docker version
          sudo docker --version
          # Check docker-compose version
          sudo docker compose version
    
    - name: Depoy Calcom Stack
      uses: appleboy/ssh-action@v1.0.3
      with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd calcom
            echo "Stopping and removing existing docker-compose containers..."
            sudo docker compose down 
            echo "Starting docker-compose..."
            sudo docker compose -f docker-compose-prod.yaml up -d
    
    